const app = document.querySelector('#app');
const toast = document.querySelector('.toast');
const navLinks = [...document.querySelectorAll('.nav-link')];
const competitions = [
  { name: 'Auckland Spring Open', meta: 'Sep 28 · Auckland, NZ · 142 competitors', status: 'live', label: 'Live', symbol: '✦' },
  { name: 'Wellington Winter Warm-up', meta: 'Oct 12 · Wellington, NZ · 86 competitors', status: 'upcoming', label: 'Upcoming', symbol: '◈' },
  { name: 'Christchurch Community Cup', meta: 'Nov 02 · Christchurch, NZ · Draft', status: 'draft', label: 'Draft', symbol: '○' }
];
const people = [
  { name: 'Mia Thompson', role: 'Competitor', events: '3x3 · 2x2 · 4x4', score: '8.42' },
  { name: 'Leo Chen', role: 'Judge', events: 'Judge · Scrambler', score: '—' },
  { name: 'Samira Patel', role: 'Delegate', events: 'All events', score: '—' },
  { name: 'Noah Williams', role: 'Competitor', events: '3x3 · OH · Pyra', score: '9.01' }
];
let currentView = 'dashboard';

function layout(title, intro, action = '') {
  return `<div class="eyebrow">NZ Cubing League</div><div class="page-heading"><div><h1>${title}</h1><p>${intro}</p></div>${action}</div>`;
}
function competitionRows() { return competitions.map(c => `<div class="competition-item"><div class="comp-symbol">${c.symbol}</div><div><h3>${c.name}</h3><p>${c.meta}</p></div><span class="status ${c.status}">${c.label}</span></div>`).join(''); }
function activityRows() { return [['Auckland Spring Open went live','Just now','activity-dot'],['Mia Thompson joined the 3x3 final','18 min ago','activity-dot'],['New scrambles generated for round 2','42 min ago','activity-dot']].map(x => `<div class="activity-row"><span class="${x[2]}"></span><div><p>${x[0]}</p><small>${x[1]}</small></div></div>`).join(''); }
function dashboard() {
  return layout('Good morning, Benji', 'Here’s what is happening across your competitions today.', '<button class="button primary" data-action="new-competition">＋ New competition</button>') + `<div class="stats-grid"><div class="stat-card"><div class="stat-top">Active competitions <span>◈</span></div><div class="stat-value">02</div><div class="stat-foot positive">↑ 1 this month</div></div><div class="stat-card"><div class="stat-top">Registered competitors <span>♙</span></div><div class="stat-value">228</div><div class="stat-foot positive">↑ 18% vs last month</div></div><div class="stat-card"><div class="stat-top">Results submitted <span>✓</span></div><div class="stat-value">94%</div><div class="stat-foot positive">↑ 4.2% completion</div></div><div class="stat-card"><div class="stat-top">People in workspace <span>♧</span></div><div class="stat-value">36</div><div class="stat-foot neutral">6 roles active</div></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Recent competitions</h2><button class="text-link" data-view-link="competitions">View all →</button></div>${competitionRows()}</section><section class="panel"><div class="panel-heading"><h2>Activity</h2><button class="text-link">This week⌄</button></div>${activityRows()}</section></div>`;
}
function competitionsView() { return layout('Competitions', 'Create, configure, and run every event from one place.', '<button class="button primary" data-action="new-competition">＋ New competition</button>') + `<section class="panel"><div class="panel-heading"><h2>All competitions <span class="muted">(${competitions.length})</span></h2><button class="button secondary">Filter⌄</button></div>${competitionRows()}</section>`; }
function peopleView() { return layout('People', 'Manage workspace members and their competition permissions.', '<button class="button primary" data-action="invite">＋ Invite person</button>') + `<section class="panel"><div class="panel-heading"><h2>Workspace members</h2><button class="button secondary">All roles⌄</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Person</th><th>Role</th><th>Events</th><th>Best average</th></tr></thead><tbody>${people.map(p => `<tr><td><div class="person"><span class="mini-avatar">${p.name.split(' ').map(n=>n[0]).join('')}</span><strong>${p.name}</strong></div></td><td>${p.role}</td><td>${p.events}</td><td>${p.score}</td></tr>`).join('')}</tbody></table></div></section>`; }
function resultsView() { return layout('Live results', 'Follow the leaderboard as judges submit official results.', '<button class="button secondary" data-action="export">↧ Export CSV</button>') + `<section class="panel"><div class="panel-heading"><h2>Auckland Spring Open · 3x3 final</h2><span class="status live">● Live</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Competitor</th><th>Average</th><th>Solves</th><th>Status</th></tr></thead><tbody>${[['01','Mia Thompson','8.42','8.91 · 8.21 · 8.14','Official'],['02','Noah Williams','9.01','9.20 · 8.88 · 8.94','Official'],['03','Olivia Martin','9.37','9.44 · 9.31 · 9.36','Awaiting judge']].map(r=>`<tr><td>${r[0]}</td><td><div class="person"><span class="mini-avatar">${r[1].split(' ').map(n=>n[0]).join('')}</span><strong>${r[1]}</strong></div></td><td><strong>${r[2]}</strong></td><td>${r[3]}</td><td><span class="status ${r[4]==='Official'?'live':'upcoming'}">${r[4]}</span></td></tr>`).join('')}</tbody></table></div></section>`; }
function judgingView() { return layout('Judging desk', 'Enter and verify attempts assigned to your judging station.', '<span class="status live">Station 04 · Online</span>') + `<section class="panel"><div class="panel-heading"><h2>Assigned scorecards</h2><span class="muted">3 remaining</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Competitor</th><th>Event</th><th>Attempt 1</th><th>Attempt 2</th><th>Action</th></tr></thead><tbody>${['Olivia Martin','Ethan Hall','Grace Kim'].map((n,i)=>`<tr><td><div class="person"><span class="mini-avatar">${n.split(' ').map(x=>x[0]).join('')}</span><strong>${n}</strong></div></td><td>3x3 round 2</td><td><input class="score-input" placeholder="8.42" /></td><td><input class="score-input" placeholder="DNF" /></td><td><button class="button primary save-score">Save</button></td></tr>`).join('')}</tbody></table></div></section>`; }
function scramblesView() { return layout('Scrambles', 'Generate, lock, and distribute fair scrambles for each round.', '<button class="button primary" data-action="generate">＋ Generate scrambles</button>') + `<div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Round 2 · 3x3</h2><span class="status live">Locked</span></div><p class="muted">12 scrambles · Generated Sep 20 at 09:14</p><div class="event-chips"><span class="event-chip selected">Scramble 01</span><span class="event-chip">Scramble 02</span><span class="event-chip">Scramble 03</span><span class="event-chip">Scramble 04</span></div><div class="empty-state">Scrambles are hidden from competitors until their scorecard is assigned.</div></section><section class="panel"><div class="panel-heading"><h2>Events</h2></div><div class="competition-item"><div class="comp-symbol">3</div><div><h3>3x3 Cube</h3><p>4 rounds · 48 scrambles</p></div><span class="status live">Ready</span></div><div class="competition-item"><div class="comp-symbol">2</div><div><h3>2x2 Cube</h3><p>3 rounds · Not generated</p></div><span class="status upcoming">Pending</span></div></section></div>`; }
function settingsView() { return layout('Workspace settings', 'Set your league identity, roles, and default competition preferences.') + `<section class="panel"><div class="form-grid"><div class="field"><label>Workspace name</label><input value="NZ Cubing League" /></div><div class="field"><label>Timezone</label><select><option>Pacific/Auckland (UTC+12)</option><option>Australia/Sydney (UTC+10)</option></select></div><div class="field full"><label>Default competition roles</label><div class="event-chips"><span class="event-chip selected">Delegate</span><span class="event-chip selected">Judge</span><span class="event-chip selected">Scrambler</span><span class="event-chip selected">Score taker</span><span class="event-chip">Moderator</span></div></div></div><div class="form-actions"><button class="button secondary">Cancel</button><button class="button primary" data-action="save">Save changes</button></div></section>`; }
function render(view = currentView) { currentView = view; const views = {dashboard, competitions:competitionsView, people:peopleView, results:resultsView, judging:judgingView, scrambles:scramblesView, settings:settingsView}; app.innerHTML = views[view](); navLinks.forEach(link => link.classList.toggle('active', link.dataset.view === view)); document.querySelector('.breadcrumbs').innerHTML = `NZ Cubing League <span>/</span> <strong>${view[0].toUpperCase()+view.slice(1)}</strong>`; }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
function newCompetition() { app.innerHTML = layout('New competition', 'Set up the essentials, then invite your team.') + `<section class="panel"><div class="form-grid"><div class="field full"><label>Competition name</label><input id="competition-name" placeholder="e.g. Auckland Summer Open" autofocus /></div><div class="field"><label>Start date</label><input type="date" value="2026-10-12" /></div><div class="field"><label>Location</label><input placeholder="City, country" /></div><div class="field full"><label>Events</label><div class="event-chips"><span class="event-chip selected">3x3</span><span class="event-chip selected">2x2</span><span class="event-chip">4x4</span><span class="event-chip">OH</span><span class="event-chip">Pyraminx</span></div></div></div><div class="form-actions"><button class="button secondary" data-view-link="competitions">Cancel</button><button class="button primary" data-action="create">Create competition</button></div></section>`; }
navLinks.forEach(link => link.addEventListener('click', e => { e.preventDefault(); render(link.dataset.view); }));
document.addEventListener('click', e => { const action = e.target.closest('[data-action]')?.dataset.action; const view = e.target.closest('[data-view-link]')?.dataset.viewLink; if (view) render(view); if (action === 'new-competition') newCompetition(); if (action === 'invite') showToast('Invite link copied to clipboard'); if (action === 'generate') showToast('12 fresh scrambles generated and locked'); if (action === 'export') showToast('Results CSV is ready to download'); if (action === 'save') showToast('Workspace settings saved'); if (action === 'create') { showToast('Competition created as a draft'); render('competitions'); } if (e.target.closest('.save-score')) { e.target.textContent='Saved'; e.target.disabled=true; showToast('Scorecard saved and marked official'); } });
document.querySelector('.mobile-menu').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open'));
render();
