const app=document.querySelector('#app');
const toast=document.querySelector('.toast');
const contests=[
 {name:'Auckland Spring Open',date:'28 Sep 2026',place:'Auckland, New Zealand',type:'Unofficial',state:'open',label:'Registration open',events:'3x3 · 2x2 · 4x4'},
 {name:'Wellington Winter Warm-up',date:'12 Oct 2026',place:'Wellington, New Zealand',type:'Community',state:'soon',label:'Coming soon',events:'3x3 · OH · Pyraminx'},
 {name:'Christchurch Community Cup',date:'02 Nov 2026',place:'Christchurch, New Zealand',type:'Community',state:'soon',label:'Coming soon',events:'3x3 · 2x2'},
 {name:'North Shore Speed Challenge',date:'14 Aug 2026',place:'Takapuna, New Zealand',type:'Unofficial',state:'past',label:'Results available',events:'3x3 · 4x4 · 5x5'},
 {name:'Otago Cube Meetup',date:'01 Aug 2026',place:'Dunedin, New Zealand',type:'Meetup',state:'past',label:'Results available',events:'3x3 · 2x2'},
 {name:'Rotorua Summer Solve',date:'18 Dec 2026',place:'Rotorua, New Zealand',type:'Community',state:'soon',label:'Coming soon',events:'3x3 · Skewb'}
];
const results=[['01','Mia Thompson','Auckland Spring Open','8.42'],['02','Noah Williams','Auckland Spring Open','9.01'],['03','Olivia Martin','North Shore Speed Challenge','9.37'],['04','Ethan Hall','Wellington Winter Warm-up','10.12']];
const card=c=>`<article class="contest-card"><div class="card-top"><span class="eyebrow">${c.type}</span><span class="badge ${c.state}">${c.label}</span></div><h3>${c.name}</h3><p>${c.date}<br>${c.place}</p><div class="card-footer">${c.events}</div></article>`;
function home(){return `<section class="hero"><div class="container hero-grid"><div><div class="kicker">Competition directory</div><h1>Find your next solve.</h1><p>Discover cubing competitions, follow live results, and keep up with the people making the community move.</p><div class="hero-links"><a class="button blue" href="#competitions" data-route="competitions">Browse competitions</a><a class="quiet-link" href="#register" data-route="register">Organize an event →</a></div></div><div class="hero-art" aria-hidden="true"><div class="cube-stack">${[1,2,3].map(()=>'<div class="cube"><span></span><span></span><span></span><span></span></div>').join('')}</div></div></div></section><section class="section"><div class="container"><div class="section-heading"><div><div class="eyebrow">On the calendar</div><h2>Upcoming competitions</h2></div><a href="#competitions" data-route="competitions">See all competitions →</a></div><div class="filters"><button class="filter selected">All events</button><button class="filter">New Zealand</button><button class="filter">Unofficial</button><button class="filter">Community meets</button></div><div class="contest-grid">${contests.slice(0,3).map(card).join('')}</div></div></section><section class="split-section"><div class="container section split-grid"><div><div class="eyebrow">Latest results</div><div class="section-heading"><h2>Recently posted</h2><a href="#results" data-route="results">View results →</a></div><div class="results-list">${results.slice(0,3).map(r=>`<div class="result-row"><span class="rank">${r[0]}</span><div><strong>${r[1]}</strong><small>${r[2]}</small></div><span class="result-value">${r[3]}</span><span>3x3 avg</span></div>`).join('')}</div></div><aside class="stat-box"><h3>Make it official.</h3><p>Running a local meet? Create a listing, invite your team, and publish results in one calm workspace.</p><a href="#register" data-route="register">Start organizing →</a></aside></div></section><section class="section directory"><div class="container"><div class="section-heading"><div><div class="eyebrow">Explore</div><h2>More from the community</h2></div><a href="#rankings" data-route="rankings">See rankings →</a></div><div class="contest-grid">${contests.slice(3).map(card).join('')}</div></div></section>`}
function competitions(){return `<div class="page-shell"><div class="container"><div class="eyebrow">Directory</div><h1>Competitions</h1><p class="intro">Browse upcoming and archived community competitions. Filter by region, format, or status to find the right event.</p><div class="search-bar"><input placeholder="Search competitions or locations" aria-label="Search competitions"><button data-action="search">Search</button></div><div class="filters"><button class="filter selected">All competitions</button><button class="filter">Upcoming</button><button class="filter">Results available</button><button class="filter">Community</button></div><div class="contest-grid">${contests.map(card).join('')}</div></div></div>`}
function resultsPage(){return `<div class="page-shell"><div class="container"><div class="eyebrow">Performance archive</div><h1>Results</h1><p class="intro">A simple view of recently submitted competition results and personal performances.</p><div class="panel"><div class="results-list">${results.concat([['05','Grace Kim','Otago Cube Meetup','11.03']]).map(r=>`<div class="result-row"><span class="rank">${r[0]}</span><div><strong>${r[1]}</strong><small>${r[2]}</small></div><span class="result-value">${r[3]}</span><span>3x3 avg</span></div>`).join('')}</div></div></div></div>`}
function rankings(){return `<div class="page-shell"><div class="container"><div class="eyebrow">Community leaderboard</div><h1>Rankings</h1><p class="intro">Track standout averages from the Turntable community. Rankings are grouped by event and update as results are published.</p><div class="panel"><div class="filters"><button class="filter selected">3x3 average</button><button class="filter">2x2 average</button><button class="filter">Single</button></div><div class="results-list">${results.map(r=>`<div class="result-row"><span class="rank">${r[0]}</span><div><strong>${r[1]}</strong><small>New Zealand · ${r[2]}</small></div><span class="result-value">${r[3]}</span><span>Average</span></div>`).join('')}</div></div></div></div>`}
function info(title,eyebrow,text,button){return `<div class="page-shell"><div class="container"><div class="panel"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="intro">${text}</p>${button||''}</div></div></div>`}
function render(route=location.hash.slice(1)||'home'){const pages={home,competitions,results,rankings};app.innerHTML=pages[route]?pages[route]():route==='about'?info('A better place for local cubing.','About Turntable','Turntable is an original, community-first tool for discovering competitions, publishing results, and giving organizers a friendly place to run their events.','<a class="button blue" href="#register" data-route="register">Get started</a>'):route==='register'?info('Create your account.','Join the community','Save competitions, follow results, and help organize the next great meet.','<button class="button blue" data-action="signup">Create account</button>'):info('Welcome back.','Account access','Sign in to manage your competitions and community profile.','<button class="button blue" data-action="login">Log in</button>');document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));window.scrollTo({top:0,behavior:'smooth'})}
function notify(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}
document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route){e.preventDefault();history.pushState({},'',`#${route}`);render(route)}if(e.target.closest('.filter')){document.querySelectorAll('.filter').forEach(b=>b.classList.remove('selected'));e.target.closest('.filter').classList.add('selected')}if(e.target.closest('[data-action]'))notify('Thanks — this demo action is ready to connect to your backend.');});document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.site-nav').classList.toggle('open'));window.addEventListener('popstate',()=>render());render();
